"""
Warlpiri keyword recognition using DTW.
Replaces librosa with python_speech_features + scipy for Android compatibility.
MFCC parameters tuned to match librosa defaults (n_fft=2048, hop_length=512 at 16kHz)
so that keyword_mfcc_android.json (generated by precompute_mfcc_release.py) aligns
with the features computed here at inference time.
"""

import json
import math
import os

import numpy as np
import scipy.io.wavfile
import scipy.signal

# python_speech_features and webrtcvad have Android wheels via Chaquopy.
# Imported lazily so the module loads on Mac/Linux dev environments too.
try:
    import python_speech_features as psf
    _PSF_AVAILABLE = True
except ImportError:
    psf = None
    _PSF_AVAILABLE = False

try:
    import webrtcvad as _webrtcvad_mod
    _WEBRTCVAD_AVAILABLE = True
except ImportError:
    _webrtcvad_mod = None
    _WEBRTCVAD_AVAILABLE = False

_RELEASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_DATA_DIR    = os.path.join(_RELEASE_DIR, "data", "warlpiri")

SAMPLE_RATE          = 16000
N_MFCC               = 13
VAD_AGGRESSIVENESS   = 2
VAD_FRAME_DURATION   = 30       # ms
MIN_SEGMENT_DURATION = 0.15     # seconds

# MFCC params matched to librosa defaults (n_fft=2048, hop_length=512 at 16kHz)
_WIN_LEN  = 0.128   # 2048 / 16000
_WIN_STEP = 0.032   # 512  / 16000
_N_FFT    = 2048
_N_FILT   = 26
_DELTA_N  = 4       # half-window for delta; matches librosa width=9 approximation

DTW_THRESHOLD    = 200.0
FRAME_RATIO_LIMIT = 3.0

# prefer android-specific precomputed MFCCs; fall back to original
_MFCC_FILE = "keyword_mfcc_android.json"
if not os.path.exists(os.path.join(_DATA_DIR, _MFCC_FILE)):
    _MFCC_FILE = "keyword_mfcc.json"


def _load(filename: str) -> dict:
    path = os.path.join(_DATA_DIR, filename)
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


KEYWORD_MFCC        = _load(_MFCC_FILE)
KEYWORD_SYMPTOM_MAP = _load("keyword_symptom_map.json")

_KEYWORD_REFS: dict[str, list[np.ndarray]] = {}
for keyword, data in KEYWORD_MFCC.items():
    arr = np.array(data)
    if arr.ndim == 2:
        _KEYWORD_REFS[keyword] = [arr]
    elif arr.ndim == 3:
        _KEYWORD_REFS[keyword] = [arr[i] for i in range(arr.shape[0])]


def _load_wav(audio_path: str) -> tuple[np.ndarray, int] | tuple[None, None]:
    """Load WAV file as float32 mono array at SAMPLE_RATE."""
    try:
        sr, data = scipy.io.wavfile.read(audio_path)

        if data.dtype == np.int16:
            data = data.astype(np.float32) / 32768.0
        elif data.dtype == np.int32:
            data = data.astype(np.float32) / 2147483648.0
        elif data.dtype == np.uint8:
            data = (data.astype(np.float32) - 128.0) / 128.0
        else:
            data = data.astype(np.float32)

        if data.ndim > 1:
            data = data.mean(axis=1)

        if sr != SAMPLE_RATE:
            gcd = math.gcd(sr, SAMPLE_RATE)
            data = scipy.signal.resample_poly(data, SAMPLE_RATE // gcd, sr // gcd)

        return data.astype(np.float32), SAMPLE_RATE
    except Exception as e:
        print(f"wav load failed: {e}")
        return None, None


def _trim_silence(audio: np.ndarray, top_db: float = 20.0) -> np.ndarray:
    """Energy-based silence trimming equivalent to librosa.effects.trim."""
    frame_length = 2048
    hop_length   = 512
    n_frames     = max(1, 1 + (len(audio) - frame_length) // hop_length)

    rms_db = np.full(n_frames, -120.0)
    for i in range(n_frames):
        start  = i * hop_length
        frame  = audio[start:start + frame_length]
        rms    = np.sqrt(np.mean(frame ** 2) + 1e-10)
        rms_db[i] = 20.0 * np.log10(rms)

    threshold  = rms_db.max() - top_db
    non_silent = np.where(rms_db >= threshold)[0]
    if len(non_silent) == 0:
        return audio

    start_sample = non_silent[0] * hop_length
    end_sample   = min((non_silent[-1] + 1) * hop_length + frame_length, len(audio))
    return audio[start_sample:end_sample]


def _extract_mfcc(audio: np.ndarray, sr: int = SAMPLE_RATE) -> np.ndarray | None:
    """
    Extract 39-dim (13 MFCC + 13 delta + 13 delta-delta) feature matrix.
    Parameters match librosa.feature.mfcc defaults so features align with
    references in keyword_mfcc_android.json.
    """
    if not _PSF_AVAILABLE:
        print("python_speech_features not available - Warlpiri audio recognition disabled")
        return None
    if len(audio) == 0:
        return None
    try:
        mfcc_frames = psf.mfcc(
            audio, samplerate=sr,
            winlen=_WIN_LEN, winstep=_WIN_STEP,
            numcep=N_MFCC, nfilt=_N_FILT, nfft=_N_FFT,
            preemph=0.0, appendEnergy=False
        )  # (n_frames, 13)

        delta1 = psf.delta(mfcc_frames, N=_DELTA_N)   # (n_frames, 13)
        delta2 = psf.delta(delta1,      N=_DELTA_N)   # (n_frames, 13)

        # transpose to (13, n_frames) then vstack → (39, n_frames)
        return np.vstack([mfcc_frames.T, delta1.T, delta2.T])
    except Exception as e:
        print(f"mfcc extraction failed: {e}")
        return None


def _dtw_distance(seq1: np.ndarray, seq2: np.ndarray) -> float:
    """Normalised DTW distance between two (n_features, n_frames) matrices."""
    s1 = seq1.T
    s2 = seq2.T
    n, m = len(s1), len(s2)

    cost = np.full((n, m), np.inf)
    cost[0, 0] = np.linalg.norm(s1[0] - s2[0])
    for i in range(1, n):
        cost[i, 0] = cost[i - 1, 0] + np.linalg.norm(s1[i] - s2[0])
    for j in range(1, m):
        cost[0, j] = cost[0, j - 1] + np.linalg.norm(s1[0] - s2[j])
    for i in range(1, n):
        for j in range(1, m):
            cost[i, j] = np.linalg.norm(s1[i] - s2[j]) + min(
                cost[i - 1, j], cost[i, j - 1], cost[i - 1, j - 1]
            )
    return cost[n - 1, m - 1] / (n + m)


def _segment_audio(audio: np.ndarray, sr: int = SAMPLE_RATE) -> list:
    """WebRTC VAD speech segmentation."""
    if not _WEBRTCVAD_AVAILABLE:
        # fallback: treat whole audio as one segment
        return [audio] if len(audio) >= int(MIN_SEGMENT_DURATION * sr) else []
    vad          = _webrtcvad_mod.Vad(VAD_AGGRESSIVENESS)
    frame_length = int(sr * VAD_FRAME_DURATION / 1000)
    min_samples  = int(MIN_SEGMENT_DURATION * sr)
    segments     = []
    current      = []

    for i in range(0, len(audio) - frame_length, frame_length):
        frame       = audio[i:i + frame_length]
        frame_bytes = (frame * 32768).astype(np.int16).tobytes()
        try:
            is_speech = vad.is_speech(frame_bytes, sr)
        except Exception:
            is_speech = False

        if is_speech:
            current.extend(frame)
        else:
            if len(current) >= min_samples:
                segments.append(np.array(current, dtype=np.float32))
            current = []

    if len(current) >= min_samples:
        segments.append(np.array(current, dtype=np.float32))
    return segments


def _match_segment(query_mfcc: np.ndarray, allowed_keywords=None) -> tuple[str, float] | None:
    """DTW match query against keyword references. Pass allowed_keywords to restrict search."""
    refs = (
        _KEYWORD_REFS if allowed_keywords is None
        else {k: v for k, v in _KEYWORD_REFS.items() if k in allowed_keywords}
    )
    query_frames  = query_mfcc.shape[1]
    best_keyword  = None
    best_distance = float("inf")

    for keyword, ref_list in refs.items():
        for ref_mfcc in ref_list:
            ref_frames = ref_mfcc.shape[1]
            ratio = max(query_frames, ref_frames) / max(min(query_frames, ref_frames), 1)
            if ratio > FRAME_RATIO_LIMIT:
                continue
            dist = _dtw_distance(query_mfcc, ref_mfcc)
            if dist < best_distance:
                best_distance = dist
                best_keyword  = keyword

    if best_distance <= DTW_THRESHOLD:
        return best_keyword, best_distance
    return None


def _distance_to_confidence(distance: float) -> float:
    centre = DTW_THRESHOLD / 2.0
    scale  = DTW_THRESHOLD / 8.0
    score  = 1.0 / (1.0 + np.exp((distance - centre) / scale))
    return round(float(score), 3)


def recognize(audio_path: str, allowed_keywords=None) -> dict:
    base = {"input_type": "audio_warlpiri", "audio_path": audio_path}

    if not _KEYWORD_REFS:
        return {**base, "recognized": False,
                "error": "no keyword references loaded - run precompute_mfcc_release.py first"}

    if not os.path.exists(audio_path):
        return {**base, "recognized": False, "error": f"audio file not found: {audio_path}"}

    audio, sr = _load_wav(audio_path)
    if audio is None:
        return {**base, "recognized": False, "error": "failed to load audio"}

    audio = _trim_silence(audio)

    if len(audio) == 0:
        return {**base, "recognized": False, "error": "audio is empty or silent"}

    segments = _segment_audio(audio, sr)
    if not segments:
        return {**base, "recognized": False,
                "error": "no speech detected - please speak clearly and try again"}

    matched_keywords: dict[str, float] = {}
    for segment in segments:
        mfcc = _extract_mfcc(segment)
        if mfcc is None:
            continue
        result = _match_segment(mfcc, allowed_keywords)
        if result:
            keyword, distance = result
            if keyword not in matched_keywords or distance < matched_keywords[keyword]:
                matched_keywords[keyword] = distance

    if not matched_keywords:
        return {
            **base,
            "recognized": False, "matched_keywords": {}, "symptoms": [],
            "confidence": 0.0, "message": "could not recognise any Warlpiri keywords - please try again"
        }

    symptoms       = []
    keyword_scores = {}
    for keyword, distance in matched_keywords.items():
        symptom = KEYWORD_SYMPTOM_MAP.get(keyword)
        if symptom and symptom not in symptoms:
            symptoms.append(symptom)
        keyword_scores[keyword] = round(distance, 3)

    best_distance = min(matched_keywords.values())
    confidence    = _distance_to_confidence(best_distance)

    return {
        **base,
        "recognized": True, "matched_keywords": keyword_scores, "symptoms": symptoms,
        "confidence": confidence, "segments_detected": len(segments),
        "segments_matched": len(matched_keywords)
    }


def list_keywords() -> list:
    return list(_KEYWORD_REFS.keys())
